# Site settings
email: marco.perez.cetis76@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: TICs - C76
description: Blog de apoyo para la clase de TICS impartida en el cetys 76
url: "https://marcoc76.github.io"
twitter_username: 
default_img: https://unsplash.it/200/300?image=1074

# Profile settings
name: Ing. Marco Antonio Perez
profile_img: https://unsplash.it/200/300?image=883
profile: Ing. Marco Antonio Perez Ingeniero en computacion, egresado de la UNAM, actualmente trabajando en el CETiS 76 como docente de TICs y Fisica
social:
  

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
