# Site settings
email: marco.perez.cetis76@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Fisica - C76
description: Blog de apoyo para la clase de Fisica impartida en el cetys 76
url: "https://marcoc76.github.io"
twitter_username: 
default_img: https://github.com/marcoC76/marcoc76.github.io/blob/master/media/intro.jpg?raw=true

# Profile settings
name: Ing. Marco Antonio Perez
profile_img: https://avatars3.githubusercontent.com/u/22418639?v=3&s=460
profile: Ingeniero en computacion Marco Antonio Perez, egresado de la UNAM, actualmente trabajando en el CETyS 76 como docente de TICs y Fisica. marco.perez.cetis76@gmail.com
social:
  

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
